disable dh_auto_test due to error
$ make -j1 test
cd src/test && qmake && make test
Project WARNING: CONFIG+=qtestlib is deprecated. Use QT+=testlib instead.
make[1]: Entering directory '/home/barak/src/git/debian-src/stopmotion/src/test'
g++ -c -m64 -pipe -g -Wall -W -D_REENTRANT -fPIE -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/home/barak/src/git/debian-src/stopmotion/src/test\" -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../.. -isystem /usr/include/libxml2 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -o build/debug/tstopmotionundo.o tstopmotionundo.cpp
tstopmotionundo.cpp: In constructor ‘TestStopmotionUndo::TestStopmotionUndo()’:
tstopmotionundo.cpp:204:34: error: invalid new-expression of abstract class type ‘MockFrontend’
  mockFrontend = new MockFrontend();
                                  ^
tstopmotionundo.cpp:170:7: note:   because the following virtual functions are pure within ‘MockFrontend’:
 class MockFrontend : public Frontend {
       ^
In file included from ../../src/domain/animation/scene.h:25:0,
                 from tstopmotionundo.cpp:31:
../../src/presentation/frontends/frontend.h:94:15: note: 	virtual void Frontend::reportError(const char*, Frontend::ErrorType)
  virtual void reportError(const char *message, ErrorType type) = 0;
               ^
../../src/presentation/frontends/frontend.h:106:15: note: 	virtual void Frontend::fatalError(Frontend::Error)
  virtual void fatalError(Error) = 0;
               ^
Makefile:800: recipe for target 'build/debug/tstopmotionundo.o' failed